name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Deps
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Build for Production
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
